on:
  push:
    branches:
      - main
    paths:
      - 'packages/kitbook/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.15.0

      - run: pnpm install
      
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: './packages/kitbook/package.json'
          access: 'public'
          tag: 'alpha'